### ISSUE TITLE
output empty

### ISSUE THREAD

**Issue by camattelaer** [CCPBioSim/CodeEntropy#20]
Hi

I'm trying to calculate entropy of my system. With ntwf=-1 in my amber input file, forces are being written to the trajectory.

The command i use is this: 
`$ CodeEntropyPoseidon -f "../00_StructurePreparation/complex_solv.prmtop" "../04_MD/07_md.nc" --selectString "protein" -t 32 -b 1 -e -1 --step 100 --excludedResnames "Cl-" "08K" -o CodeEntropy.out `

followed by this output in the terminal: 
filePath ['../00_StructurePreparation/complex_solv.prmtop', '../04_MD/07_md.nc'] 
 selectionString protein
 start 1
 end -1
 step 100
 temp 298.0
 thread 32
 outFile CodeEntropy.out
 csvOutFile outfile.csv
 rescsvOutFile res_outfile.csv
 moutFile 
 nmdFile 
 rotationalAxis ['C', 'CA', 'N']
 cutShell 
 puteAtomNum 1
 excludedResnanes ['Cl-', '08K']
 waterResnames WAT
 solventResnames 
 doMolEntropy 
 doResEntropy 
 doUAEntropy 
 topogEntropyMethod 
 doSolMolEntropy 
 doSolResEntropy 
 doSolUAEntropy 
 doSolContact 
Number of atoms      : 2121
Number of frames     : 191
total time 0:02:15.423818

but only the outfile.csv gets written and it is empty. I didn't find any suggestion why this occurs?

Kind regards and thanks in advance

Charles-Alexandre Mattelaer

**Comment by camattelaer** [comment]
Sorry, new to the code, was running without any flag to actually calculate something, e.g --wm

**Comment by skfegan** [comment]
No need to be sorry. I have made that mistake myself. The next version of the code will have different defaults for output ... hopefully this will make it easier to use.
