### ISSUE TITLE
Ask user to reduce the system using MDAHelper instead of doing it with arg_selector

### ISSUE THREAD

**Issue by DonaldChung-HK** [CCPBioSim/CodeEntropy#4]
MDanalysis provide a more robust and consistent way of selecting atom so reducing the system to the interested part before putting it into the dataCotainer to  save memory and reduce chance of bug.

**Comment by DonaldChung-HK** [comment]
In long term, we might want to remove the arg_selector from all Argo's CodeEntropy code as it is just an artifact of his earlier self-coded atom_selector.

**Comment by skfegan** [comment]
We have changed to using MDAnalysis universe object instead of Argo's dataContainer.
